[project]
name = "player-tracking-data"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "great-tables>=0.21.0",
    "matplotlib>=3.10.9",
    "polars>=1.41.2",
]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "jupyter>=1.1.1",
    "nbclient>=0.11.0",
]
